export const sources = [
  {
    id: "guardian",
    name: "The Guardian",
    shortName: "Guardian",
    color: "#052962",
    feedUrl: "https://www.theguardian.com/world/rss",
  },
  {
    id: "bbc",
    name: "BBC News",
    shortName: "BBC",
    color: "#bb1919",
    feedUrl: "https://feeds.bbci.co.uk/news/world/rss.xml",
  },
  {
    id: "france24",
    name: "France 24",
    shortName: "France 24",
    color: "#009fe3",
    feedUrl: "https://www.france24.com/fr/rss",
  },
  {
    id: "rtve",
    name: "RTVE Noticias",
    shortName: "RTVE",
    color: "#f97316",
    feedUrl: "https://www.rtve.es/noticias/",
  },
  {
    id: "tagesschau",
    name: "tagesschau",
    shortName: "tagesschau",
    color: "#1d4ed8",
    feedUrl: "https://www.tagesschau.de/infoservices/alle-meldungen-100~rss2.xml",
  },
  {
    id: "rbb24",
    name: "rbb24",
    shortName: "rbb24",
    color: "#dc2626",
    feedUrl: "https://www.rbb24.de/index.xml/feed=rss.xml",
  },
  {
    id: "deutschlandfunk",
    name: "Deutschlandfunk",
    shortName: "DLF",
    color: "#0f766e",
    feedUrl: "https://www.deutschlandfunk.de/nachrichten-100.rss",
  },
  {
    id: "tagesspiegel",
    name: "Der Tagesspiegel",
    shortName: "Tagesspiegel",
    color: "#7c3aed",
    feedUrl: "https://www.tagesspiegel.de/contentexport/feed/home",
  },
] as const;
